name: .NET 9 Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore all projects
        run: |
          find . -name "*.csproj" -print0 | xargs -0 -n1 dotnet restore

      - name: Build all projects
        run: |
          find . -name "*.csproj" -print0 | xargs -0 -n1 dotnet build --no-restore --configuration Release

      # - name: Restore dependencies
      #   run: |
      #     dotnet restore src/API/API.csproj
      #     dotnet restore src/Application/Application.csproj
      #     dotnet restore src/Domain/Domain.csproj
      #     dotnet restore src/Infrastructure/Infrastructure.csproj

      # - name: Build projects
      #   run: |
      #     dotnet build src/API/API.csproj --no-restore --configuration Release
      #     dotnet build src/Application/Application.csproj --no-restore --configuration Release
      #     dotnet build src/Domain/Domain.csproj --no-restore --configuration Release
      #     dotnet build src/Infrastructure/Infrastructure.csproj --no-restore --configuration Release
